package cc.momas.customer.pojo;

public class Categories {
    private Integer categoryId;
    private String categoryName;
    private String categoryTitle;
    private Integer categoryPid;
    private Integer categoryIsdel;
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.CATEGORY_ID
     *
     * @param categoryId the value for categories.CATEGORY_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.CATEGORY_NAME
     *
     * @return the value of categories.CATEGORY_NAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.CATEGORY_NAME
     *
     * @param categoryName the value for categories.CATEGORY_NAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.CATEGORY_TITLE
     *
     * @return the value of categories.CATEGORY_TITLE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getCategoryTitle() {
        return categoryTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.CATEGORY_TITLE
     *
     * @param categoryTitle the value for categories.CATEGORY_TITLE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setCategoryTitle(String categoryTitle) {
        this.categoryTitle = categoryTitle == null ? null : categoryTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.CATEGORY_PID
     *
     * @return the value of categories.CATEGORY_PID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getCategoryPid() {
        return categoryPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.CATEGORY_PID
     *
     * @param categoryPid the value for categories.CATEGORY_PID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setCategoryPid(Integer categoryPid) {
        this.categoryPid = categoryPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.CATEGORY_ISDEL
     *
     * @return the value of categories.CATEGORY_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getCategoryIsdel() {
        return categoryIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.CATEGORY_ISDEL
     *
     * @param categoryIsdel the value for categories.CATEGORY_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setCategoryIsdel(Integer categoryIsdel) {
        this.categoryIsdel = categoryIsdel;
    }
}