package cc.momas.customer.pojo;

import java.util.Date;

public class Consumeorders {
    private Integer consumeordersId;
    private Integer shopId;
    private Integer usersId;
    private String consumeordersOrdercode;
    private Integer consumeordersOrdertype;
    private Integer memcardsId;
    private String memcardsCardid;
    private Integer exchanggiftsId;
    private Float consumeordersTotalmoney;
    private Float consumeordersDiscountmoney;
    private Integer consumeordersGavepoint;
    private Float consumeordersRecash;
    private String consumeordersRemark;
    private Date consumeordersCreatetime;
    private Integer consumeordersIsdel;

    private Memcards memberCard ;
    
    public Memcards getMemberCard() {
		return memberCard;
	}

	public void setMemberCard(Memcards memberCard) {
		this.memberCard = memberCard;
	}

	public Integer getConsumeordersId() {
        return consumeordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_ID
     *
     * @param consumeordersId the value for consumeorders.CONSUMEORDERS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersId(Integer consumeordersId) {
        this.consumeordersId = consumeordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.SHOP_ID
     *
     * @return the value of consumeorders.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.SHOP_ID
     *
     * @param shopId the value for consumeorders.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.USERS_ID
     *
     * @return the value of consumeorders.USERS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.USERS_ID
     *
     * @param usersId the value for consumeorders.USERS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_ORDERCODE
     *
     * @return the value of consumeorders.CONSUMEORDERS_ORDERCODE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getConsumeordersOrdercode() {
        return consumeordersOrdercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_ORDERCODE
     *
     * @param consumeordersOrdercode the value for consumeorders.CONSUMEORDERS_ORDERCODE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersOrdercode(String consumeordersOrdercode) {
        this.consumeordersOrdercode = consumeordersOrdercode == null ? null : consumeordersOrdercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_ORDERTYPE
     *
     * @return the value of consumeorders.CONSUMEORDERS_ORDERTYPE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getConsumeordersOrdertype() {
        return consumeordersOrdertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_ORDERTYPE
     *
     * @param consumeordersOrdertype the value for consumeorders.CONSUMEORDERS_ORDERTYPE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersOrdertype(Integer consumeordersOrdertype) {
        this.consumeordersOrdertype = consumeordersOrdertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.MEMCARDS_ID
     *
     * @return the value of consumeorders.MEMCARDS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsId() {
        return memcardsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.MEMCARDS_ID
     *
     * @param memcardsId the value for consumeorders.MEMCARDS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsId(Integer memcardsId) {
        this.memcardsId = memcardsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.MEMCARDS_CARDID
     *
     * @return the value of consumeorders.MEMCARDS_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsCardid() {
        return memcardsCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.MEMCARDS_CARDID
     *
     * @param memcardsCardid the value for consumeorders.MEMCARDS_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsCardid(String memcardsCardid) {
        this.memcardsCardid = memcardsCardid == null ? null : memcardsCardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.EXCHANGGIFTS_ID
     *
     * @return the value of consumeorders.EXCHANGGIFTS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getExchanggiftsId() {
        return exchanggiftsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.EXCHANGGIFTS_ID
     *
     * @param exchanggiftsId the value for consumeorders.EXCHANGGIFTS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setExchanggiftsId(Integer exchanggiftsId) {
        this.exchanggiftsId = exchanggiftsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_TOTALMONEY
     *
     * @return the value of consumeorders.CONSUMEORDERS_TOTALMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Float getConsumeordersTotalmoney() {
        return consumeordersTotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_TOTALMONEY
     *
     * @param consumeordersTotalmoney the value for consumeorders.CONSUMEORDERS_TOTALMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersTotalmoney(Float consumeordersTotalmoney) {
        this.consumeordersTotalmoney = consumeordersTotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_DISCOUNTMONEY
     *
     * @return the value of consumeorders.CONSUMEORDERS_DISCOUNTMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Float getConsumeordersDiscountmoney() {
        return consumeordersDiscountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_DISCOUNTMONEY
     *
     * @param consumeordersDiscountmoney the value for consumeorders.CONSUMEORDERS_DISCOUNTMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersDiscountmoney(Float consumeordersDiscountmoney) {
        this.consumeordersDiscountmoney = consumeordersDiscountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_GAVEPOINT
     *
     * @return the value of consumeorders.CONSUMEORDERS_GAVEPOINT
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getConsumeordersGavepoint() {
        return consumeordersGavepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_GAVEPOINT
     *
     * @param consumeordersGavepoint the value for consumeorders.CONSUMEORDERS_GAVEPOINT
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersGavepoint(Integer consumeordersGavepoint) {
        this.consumeordersGavepoint = consumeordersGavepoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_RECASH
     *
     * @return the value of consumeorders.CONSUMEORDERS_RECASH
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Float getConsumeordersRecash() {
        return consumeordersRecash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_RECASH
     *
     * @param consumeordersRecash the value for consumeorders.CONSUMEORDERS_RECASH
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersRecash(Float consumeordersRecash) {
        this.consumeordersRecash = consumeordersRecash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_REMARK
     *
     * @return the value of consumeorders.CONSUMEORDERS_REMARK
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getConsumeordersRemark() {
        return consumeordersRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_REMARK
     *
     * @param consumeordersRemark the value for consumeorders.CONSUMEORDERS_REMARK
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersRemark(String consumeordersRemark) {
        this.consumeordersRemark = consumeordersRemark == null ? null : consumeordersRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_CREATETIME
     *
     * @return the value of consumeorders.CONSUMEORDERS_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Date getConsumeordersCreatetime() {
        return consumeordersCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_CREATETIME
     *
     * @param consumeordersCreatetime the value for consumeorders.CONSUMEORDERS_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersCreatetime(Date consumeordersCreatetime) {
        this.consumeordersCreatetime = consumeordersCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumeorders.CONSUMEORDERS_ISDEL
     *
     * @return the value of consumeorders.CONSUMEORDERS_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getConsumeordersIsdel() {
        return consumeordersIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumeorders.CONSUMEORDERS_ISDEL
     *
     * @param consumeordersIsdel the value for consumeorders.CONSUMEORDERS_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setConsumeordersIsdel(Integer consumeordersIsdel) {
        this.consumeordersIsdel = consumeordersIsdel;
    }
}