package cc.momas.customer.pojo;

import java.util.Date;

public class Memcards {
	public final int GONG_LI_BIRTHDAY = 1;
	public final int NONG_LI_BIRTHDAY = 0;
    private Integer cardlevelsId;
    private Integer memcardsBirthdayDay;
    private Integer memcardsBirthdayMonth;
    private Integer memcardsBirthdaytype;
    private String memcardsCardid;
    private Date memcardsCreatetime;
    private Integer memcardsId;
    private Integer memcardsIsdel;
    private Integer memcardsIspast;
    private Integer memcardsIspointauto;
    private String memcardsMobile;
    private Float memcardsMoney;
    private String memcardsName;
    private String memcardsPassword;
    private Date memcardsPasttime;
    private String memcardsPhoto;
    private Integer memcardsPoint;
    private String memcardsReferercard;
    private Integer memcardsRefererid;
    private String memcardsReferername;
    private String memcardsSex;
    private Integer memcardsState;
    private Integer memcardsTotalcount;
    private Float memcardsTotalmoney;
    private Integer shopId;
    private Cardlevels cardlevels;
    private Categories memberCardState;
    
    
    public Categories getMemberCardState() {
		return memberCardState;
	}

	public void setMemberCardState(Categories memberCardState) {
		this.memberCardState = memberCardState;
	}

	public Cardlevels getCardlevels() {
		return cardlevels;
	}

	public void setCardlevels(Cardlevels cardlevels) {
		this.cardlevels = cardlevels;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.CARDLEVELS_ID
     *
     * @return the value of memcards.CARDLEVELS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getCardlevelsId() {
        return cardlevelsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_BIRTHDAY_DAY
     *
     * @return the value of memcards.MEMCARDS_BIRTHDAY_DAY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsBirthdayDay() {
        return memcardsBirthdayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_BIRTHDAY_MONTH
     *
     * @return the value of memcards.MEMCARDS_BIRTHDAY_MONTH
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsBirthdayMonth() {
        return memcardsBirthdayMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_BIRTHDAYTYPE
     *
     * @return the value of memcards.MEMCARDS_BIRTHDAYTYPE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsBirthdaytype() {
        return memcardsBirthdaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_CARDID
     *
     * @return the value of memcards.MEMCARDS_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsCardid() {
        return memcardsCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_CREATETIME
     *
     * @return the value of memcards.MEMCARDS_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Date getMemcardsCreatetime() {
        return memcardsCreatetime;
    }

    public Integer getMemcardsId() {
        return memcardsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_ISDEL
     *
     * @return the value of memcards.MEMCARDS_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsIsdel() {
        return memcardsIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_ISPAST
     *
     * @return the value of memcards.MEMCARDS_ISPAST
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsIspast() {
        return memcardsIspast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_ISPOINTAUTO
     *
     * @return the value of memcards.MEMCARDS_ISPOINTAUTO
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsIspointauto() {
        return memcardsIspointauto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_MOBILE
     *
     * @return the value of memcards.MEMCARDS_MOBILE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsMobile() {
        return memcardsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_MONEY
     *
     * @return the value of memcards.MEMCARDS_MONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Float getMemcardsMoney() {
        return memcardsMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_NAME
     *
     * @return the value of memcards.MEMCARDS_NAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsName() {
        return memcardsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_PASSWORD
     *
     * @return the value of memcards.MEMCARDS_PASSWORD
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsPassword() {
        return memcardsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_PASTTIME
     *
     * @return the value of memcards.MEMCARDS_PASTTIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Date getMemcardsPasttime() {
        return memcardsPasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_PHOTO
     *
     * @return the value of memcards.MEMCARDS_PHOTO
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsPhoto() {
        return memcardsPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_POINT
     *
     * @return the value of memcards.MEMCARDS_POINT
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsPoint() {
        return memcardsPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_REFERERCARD
     *
     * @return the value of memcards.MEMCARDS_REFERERCARD
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsReferercard() {
        return memcardsReferercard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_REFERERID
     *
     * @return the value of memcards.MEMCARDS_REFERERID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsRefererid() {
        return memcardsRefererid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_REFERERNAME
     *
     * @return the value of memcards.MEMCARDS_REFERERNAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsReferername() {
        return memcardsReferername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_SEX
     *
     * @return the value of memcards.MEMCARDS_SEX
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getMemcardsSex() {
        return memcardsSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_STATE
     *
     * @return the value of memcards.MEMCARDS_STATE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsState() {
        return memcardsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_TOTALCOUNT
     *
     * @return the value of memcards.MEMCARDS_TOTALCOUNT
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getMemcardsTotalcount() {
        return memcardsTotalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.MEMCARDS_TOTALMONEY
     *
     * @return the value of memcards.MEMCARDS_TOTALMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Float getMemcardsTotalmoney() {
        return memcardsTotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memcards.SHOP_ID
     *
     * @return the value of memcards.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.CARDLEVELS_ID
     *
     * @param cardlevelsId the value for memcards.CARDLEVELS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setCardlevelsId(Integer cardlevelsId) {
        this.cardlevelsId = cardlevelsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_BIRTHDAY_DAY
     *
     * @param memcardsBirthdayDay the value for memcards.MEMCARDS_BIRTHDAY_DAY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsBirthdayDay(Integer memcardsBirthdayDay) {
        this.memcardsBirthdayDay = memcardsBirthdayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_BIRTHDAY_MONTH
     *
     * @param memcardsBirthdayMonth the value for memcards.MEMCARDS_BIRTHDAY_MONTH
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsBirthdayMonth(Integer memcardsBirthdayMonth) {
        this.memcardsBirthdayMonth = memcardsBirthdayMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_BIRTHDAYTYPE
     *
     * @param memcardsBirthdaytype the value for memcards.MEMCARDS_BIRTHDAYTYPE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsBirthdaytype(Integer memcardsBirthdaytype) {
        this.memcardsBirthdaytype = memcardsBirthdaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_CARDID
     *
     * @param memcardsCardid the value for memcards.MEMCARDS_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsCardid(String memcardsCardid) {
        this.memcardsCardid = memcardsCardid == null ? null : memcardsCardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_CREATETIME
     *
     * @param memcardsCreatetime the value for memcards.MEMCARDS_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsCreatetime(Date memcardsCreatetime) {
        this.memcardsCreatetime = memcardsCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_ID
     *
     * @param memcardsId the value for memcards.MEMCARDS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsId(Integer memcardsId) {
        this.memcardsId = memcardsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_ISDEL
     *
     * @param memcardsIsdel the value for memcards.MEMCARDS_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsIsdel(Integer memcardsIsdel) {
        this.memcardsIsdel = memcardsIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_ISPAST
     *
     * @param memcardsIspast the value for memcards.MEMCARDS_ISPAST
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsIspast(Integer memcardsIspast) {
        this.memcardsIspast = memcardsIspast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_ISPOINTAUTO
     *
     * @param memcardsIspointauto the value for memcards.MEMCARDS_ISPOINTAUTO
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsIspointauto(Integer memcardsIspointauto) {
        this.memcardsIspointauto = memcardsIspointauto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_MOBILE
     *
     * @param memcardsMobile the value for memcards.MEMCARDS_MOBILE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsMobile(String memcardsMobile) {
        this.memcardsMobile = memcardsMobile == null ? null : memcardsMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_MONEY
     *
     * @param memcardsMoney the value for memcards.MEMCARDS_MONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsMoney(Float memcardsMoney) {
        this.memcardsMoney = memcardsMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_NAME
     *
     * @param memcardsName the value for memcards.MEMCARDS_NAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsName(String memcardsName) {
        this.memcardsName = memcardsName == null ? null : memcardsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_PASSWORD
     *
     * @param memcardsPassword the value for memcards.MEMCARDS_PASSWORD
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsPassword(String memcardsPassword) {
        this.memcardsPassword = memcardsPassword == null ? null : memcardsPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_PASTTIME
     *
     * @param memcardsPasttime the value for memcards.MEMCARDS_PASTTIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsPasttime(Date memcardsPasttime) {
        this.memcardsPasttime = memcardsPasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_PHOTO
     *
     * @param memcardsPhoto the value for memcards.MEMCARDS_PHOTO
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsPhoto(String memcardsPhoto) {
        this.memcardsPhoto = memcardsPhoto == null ? null : memcardsPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_POINT
     *
     * @param memcardsPoint the value for memcards.MEMCARDS_POINT
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsPoint(Integer memcardsPoint) {
        this.memcardsPoint = memcardsPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_REFERERCARD
     *
     * @param memcardsReferercard the value for memcards.MEMCARDS_REFERERCARD
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsReferercard(String memcardsReferercard) {
        this.memcardsReferercard = memcardsReferercard == null ? null : memcardsReferercard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_REFERERID
     *
     * @param memcardsRefererid the value for memcards.MEMCARDS_REFERERID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsRefererid(Integer memcardsRefererid) {
        this.memcardsRefererid = memcardsRefererid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_REFERERNAME
     *
     * @param memcardsReferername the value for memcards.MEMCARDS_REFERERNAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsReferername(String memcardsReferername) {
        this.memcardsReferername = memcardsReferername == null ? null : memcardsReferername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_SEX
     *
     * @param memcardsSex the value for memcards.MEMCARDS_SEX
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsSex(String memcardsSex) {
        this.memcardsSex = memcardsSex == null ? null : memcardsSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_STATE
     *
     * @param memcardsState the value for memcards.MEMCARDS_STATE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsState(Integer memcardsState) {
        this.memcardsState = memcardsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_TOTALCOUNT
     *
     * @param memcardsTotalcount the value for memcards.MEMCARDS_TOTALCOUNT
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsTotalcount(Integer memcardsTotalcount) {
        this.memcardsTotalcount = memcardsTotalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.MEMCARDS_TOTALMONEY
     *
     * @param memcardsTotalmoney the value for memcards.MEMCARDS_TOTALMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setMemcardsTotalmoney(Float memcardsTotalmoney) {
        this.memcardsTotalmoney = memcardsTotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memcards.SHOP_ID
     *
     * @param shopId the value for memcards.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}