package cc.momas.customer.pojo;

import java.util.Date;

public class Shops {
	

	public static final Integer HAVE_ADMIN = 1;
	public static final Integer HAVE_NOT_ADMIN = 0;
	
	private Categories categories;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_NAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_CATEGORY_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer shopCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_CONTACTNAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private String shopContactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_CONTACTTEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private String shopContacttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_ADDRESS
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private String shopAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_REMARK
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private String shopRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_ISHASSETADMIN
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer shopIshassetadmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Date shopCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.SHOP_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer shopIsdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_ID
     *
     * @return the value of shops.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_ID
     *
     * @param shopId the value for shops.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_NAME
     *
     * @return the value of shops.SHOP_NAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_NAME
     *
     * @param shopName the value for shops.SHOP_NAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_CATEGORY_ID
     *
     * @return the value of shops.SHOP_CATEGORY_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getShopCategoryId() {
        return shopCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_CATEGORY_ID
     *
     * @param shopCategoryId the value for shops.SHOP_CATEGORY_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopCategoryId(Integer shopCategoryId) {
        this.shopCategoryId = shopCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_CONTACTNAME
     *
     * @return the value of shops.SHOP_CONTACTNAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getShopContactname() {
        return shopContactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_CONTACTNAME
     *
     * @param shopContactname the value for shops.SHOP_CONTACTNAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopContactname(String shopContactname) {
        this.shopContactname = shopContactname == null ? null : shopContactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_CONTACTTEL
     *
     * @return the value of shops.SHOP_CONTACTTEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getShopContacttel() {
        return shopContacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_CONTACTTEL
     *
     * @param shopContacttel the value for shops.SHOP_CONTACTTEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopContacttel(String shopContacttel) {
        this.shopContacttel = shopContacttel == null ? null : shopContacttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_ADDRESS
     *
     * @return the value of shops.SHOP_ADDRESS
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getShopAddress() {
        return shopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_ADDRESS
     *
     * @param shopAddress the value for shops.SHOP_ADDRESS
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress == null ? null : shopAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_REMARK
     *
     * @return the value of shops.SHOP_REMARK
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getShopRemark() {
        return shopRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_REMARK
     *
     * @param shopRemark the value for shops.SHOP_REMARK
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopRemark(String shopRemark) {
        this.shopRemark = shopRemark == null ? null : shopRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_ISHASSETADMIN
     *
     * @return the value of shops.SHOP_ISHASSETADMIN
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getShopIshassetadmin() {
        return shopIshassetadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_ISHASSETADMIN
     *
     * @param shopIshassetadmin the value for shops.SHOP_ISHASSETADMIN
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopIshassetadmin(Integer shopIshassetadmin) {
        this.shopIshassetadmin = shopIshassetadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_CREATETIME
     *
     * @return the value of shops.SHOP_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Date getShopCreatetime() {
        return shopCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_CREATETIME
     *
     * @param shopCreatetime the value for shops.SHOP_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopCreatetime(Date shopCreatetime) {
        this.shopCreatetime = shopCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.SHOP_ISDEL
     *
     * @return the value of shops.SHOP_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getShopIsdel() {
        return shopIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.SHOP_ISDEL
     *
     * @param shopIsdel the value for shops.SHOP_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopIsdel(Integer shopIsdel) {
        this.shopIsdel = shopIsdel;
    }
    
    public Categories getCategories() {
		return categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}
}