package cc.momas.customer.pojo;

import java.util.Date;

public class Transferlogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer transferlogsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.USERS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_FROMMC_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer transferlogsFrommcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_FROMMC_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private String transferlogsFrommcCardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_TOMC_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer transferlogsTomcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_TOMC_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private String transferlogsTomcCardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_TRANSFERMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Float transferlogsTransfermoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_REMARK
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private String transferlogsRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Date transferlogsCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transferlogs.TRANSFERLOGS_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    private Integer transferlogsIsdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_ID
     *
     * @return the value of transferlogs.TRANSFERLOGS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getTransferlogsId() {
        return transferlogsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_ID
     *
     * @param transferlogsId the value for transferlogs.TRANSFERLOGS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsId(Integer transferlogsId) {
        this.transferlogsId = transferlogsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.SHOP_ID
     *
     * @return the value of transferlogs.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.SHOP_ID
     *
     * @param shopId the value for transferlogs.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.USERS_ID
     *
     * @return the value of transferlogs.USERS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.USERS_ID
     *
     * @param usersId the value for transferlogs.USERS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_FROMMC_ID
     *
     * @return the value of transferlogs.TRANSFERLOGS_FROMMC_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getTransferlogsFrommcId() {
        return transferlogsFrommcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_FROMMC_ID
     *
     * @param transferlogsFrommcId the value for transferlogs.TRANSFERLOGS_FROMMC_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsFrommcId(Integer transferlogsFrommcId) {
        this.transferlogsFrommcId = transferlogsFrommcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_FROMMC_CARDID
     *
     * @return the value of transferlogs.TRANSFERLOGS_FROMMC_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getTransferlogsFrommcCardid() {
        return transferlogsFrommcCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_FROMMC_CARDID
     *
     * @param transferlogsFrommcCardid the value for transferlogs.TRANSFERLOGS_FROMMC_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsFrommcCardid(String transferlogsFrommcCardid) {
        this.transferlogsFrommcCardid = transferlogsFrommcCardid == null ? null : transferlogsFrommcCardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_TOMC_ID
     *
     * @return the value of transferlogs.TRANSFERLOGS_TOMC_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getTransferlogsTomcId() {
        return transferlogsTomcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_TOMC_ID
     *
     * @param transferlogsTomcId the value for transferlogs.TRANSFERLOGS_TOMC_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsTomcId(Integer transferlogsTomcId) {
        this.transferlogsTomcId = transferlogsTomcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_TOMC_CARDID
     *
     * @return the value of transferlogs.TRANSFERLOGS_TOMC_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getTransferlogsTomcCardid() {
        return transferlogsTomcCardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_TOMC_CARDID
     *
     * @param transferlogsTomcCardid the value for transferlogs.TRANSFERLOGS_TOMC_CARDID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsTomcCardid(String transferlogsTomcCardid) {
        this.transferlogsTomcCardid = transferlogsTomcCardid == null ? null : transferlogsTomcCardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_TRANSFERMONEY
     *
     * @return the value of transferlogs.TRANSFERLOGS_TRANSFERMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Float getTransferlogsTransfermoney() {
        return transferlogsTransfermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_TRANSFERMONEY
     *
     * @param transferlogsTransfermoney the value for transferlogs.TRANSFERLOGS_TRANSFERMONEY
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsTransfermoney(Float transferlogsTransfermoney) {
        this.transferlogsTransfermoney = transferlogsTransfermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_REMARK
     *
     * @return the value of transferlogs.TRANSFERLOGS_REMARK
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getTransferlogsRemark() {
        return transferlogsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_REMARK
     *
     * @param transferlogsRemark the value for transferlogs.TRANSFERLOGS_REMARK
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsRemark(String transferlogsRemark) {
        this.transferlogsRemark = transferlogsRemark == null ? null : transferlogsRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_CREATETIME
     *
     * @return the value of transferlogs.TRANSFERLOGS_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Date getTransferlogsCreatetime() {
        return transferlogsCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_CREATETIME
     *
     * @param transferlogsCreatetime the value for transferlogs.TRANSFERLOGS_CREATETIME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsCreatetime(Date transferlogsCreatetime) {
        this.transferlogsCreatetime = transferlogsCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transferlogs.TRANSFERLOGS_ISDEL
     *
     * @return the value of transferlogs.TRANSFERLOGS_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getTransferlogsIsdel() {
        return transferlogsIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transferlogs.TRANSFERLOGS_ISDEL
     *
     * @param transferlogsIsdel the value for transferlogs.TRANSFERLOGS_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setTransferlogsIsdel(Integer transferlogsIsdel) {
        this.transferlogsIsdel = transferlogsIsdel;
    }
}