package cc.momas.customer.pojo;

public class Users {
    public final int CAN_DEL = 1;
    public final int CAN_NOT_DEL = 0;
    public final int IS_DEL = 1;
    public final int IS_NOT_DEL = 0;
    private Integer shopId;
    private Integer usersCandelete;
    private Integer usersId;
    private Integer usersIsdel;
    private String usersLoginname;
    private String usersPassword;
    private String usersRealname;
    private Integer usersRole;
    private String usersSex;
    private String usersTelephone;
    private Categories role;
    
    
    
    public Categories getRole() {
		return role;
	}

	public void setRole(Categories role) {
		this.role = role;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.SHOP_ID
     *
     * @return the value of users.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERS_CANDELETE
     *
     * @return the value of users.USERS_CANDELETE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getUsersCandelete() {
        return usersCandelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERS_ID
     *
     * @return the value of users.USERS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getUsersId() {
        return usersId;
    }

    public Integer getUsersIsdel() {
        return usersIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERS_LOGINNAME
     *
     * @return the value of users.USERS_LOGINNAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getUsersLoginname() {
        return usersLoginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERS_PASSWORD
     *
     * @return the value of users.USERS_PASSWORD
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getUsersPassword() {
        return usersPassword;
    }

    public String getUsersRealname() {
        return usersRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERS_ROLE
     *
     * @return the value of users.USERS_ROLE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public Integer getUsersRole() {
        return usersRole;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERS_SEX
     *
     * @return the value of users.USERS_SEX
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getUsersSex() {
        return usersSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERS_TELEPHONE
     *
     * @return the value of users.USERS_TELEPHONE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public String getUsersTelephone() {
        return usersTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.SHOP_ID
     *
     * @param shopId the value for users.SHOP_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    public void setUsersCandelete(Integer usersCandelete) {
        this.usersCandelete = usersCandelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERS_ID
     *
     * @param usersId the value for users.USERS_ID
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERS_ISDEL
     *
     * @param usersIsdel the value for users.USERS_ISDEL
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersIsdel(Integer usersIsdel) {
        this.usersIsdel = usersIsdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERS_LOGINNAME
     *
     * @param usersLoginname the value for users.USERS_LOGINNAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersLoginname(String usersLoginname) {
        this.usersLoginname = usersLoginname == null ? null : usersLoginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERS_PASSWORD
     *
     * @param usersPassword the value for users.USERS_PASSWORD
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersPassword(String usersPassword) {
        this.usersPassword = usersPassword == null ? null : usersPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERS_REALNAME
     *
     * @param usersRealname the value for users.USERS_REALNAME
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersRealname(String usersRealname) {
        this.usersRealname = usersRealname == null ? null : usersRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERS_ROLE
     *
     * @param usersRole the value for users.USERS_ROLE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersRole(Integer usersRole) {
        this.usersRole = usersRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERS_SEX
     *
     * @param usersSex the value for users.USERS_SEX
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersSex(String usersSex) {
        this.usersSex = usersSex == null ? null : usersSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USERS_TELEPHONE
     *
     * @param usersTelephone the value for users.USERS_TELEPHONE
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    public void setUsersTelephone(String usersTelephone) {
        this.usersTelephone = usersTelephone == null ? null : usersTelephone.trim();
    }
}