
package cc.momas.customer.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IShopWs", targetNamespace = "http://ws.customer.momas.cc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IShopWs {


    /**
     * 
     * @return
     *     returns java.util.List<cc.momas.customer.ws.Shops>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryAllShopsByNotAssociate", targetNamespace = "http://ws.customer.momas.cc/", className = "cc.momas.customer.ws.QueryAllShopsByNotAssociate")
    @ResponseWrapper(localName = "queryAllShopsByNotAssociateResponse", targetNamespace = "http://ws.customer.momas.cc/", className = "cc.momas.customer.ws.QueryAllShopsByNotAssociateResponse")
    public List<Shops> queryAllShopsByNotAssociate();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cc.momas.customer.ws.Shops>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryAllShopsByAssociate", targetNamespace = "http://ws.customer.momas.cc/", className = "cc.momas.customer.ws.QueryAllShopsByAssociate")
    @ResponseWrapper(localName = "queryAllShopsByAssociateResponse", targetNamespace = "http://ws.customer.momas.cc/", className = "cc.momas.customer.ws.QueryAllShopsByAssociateResponse")
    public List<Shops> queryAllShopsByAssociate(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cc.momas.customer.ws.Users
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryByPhone", targetNamespace = "http://ws.customer.momas.cc/", className = "cc.momas.customer.ws.QueryByPhone")
    @ResponseWrapper(localName = "queryByPhoneResponse", targetNamespace = "http://ws.customer.momas.cc/", className = "cc.momas.customer.ws.QueryByPhoneResponse")
    public Users queryByPhone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateShopsDecidezoneId", targetNamespace = "http://ws.customer.momas.cc/", className = "cc.momas.customer.ws.UpdateShopsDecidezoneId")
    @ResponseWrapper(localName = "updateShopsDecidezoneIdResponse", targetNamespace = "http://ws.customer.momas.cc/", className = "cc.momas.customer.ws.UpdateShopsDecidezoneIdResponse")
    public int updateShopsDecidezoneId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

}
