
package cc.momas.customer.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShopWsImplService", targetNamespace = "http://ws.customer.momas.cc/", wsdlLocation = "http://10.10.23.128/customer/service/shops?wsdl")
public class ShopWsImplService
    extends Service
{

    private final static URL SHOPWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOPWSIMPLSERVICE_EXCEPTION;
    private final static QName SHOPWSIMPLSERVICE_QNAME = new QName("http://ws.customer.momas.cc/", "ShopWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.10.23.128/customer/service/shops?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOPWSIMPLSERVICE_WSDL_LOCATION = url;
        SHOPWSIMPLSERVICE_EXCEPTION = e;
    }

    public ShopWsImplService() {
        super(__getWsdlLocation(), SHOPWSIMPLSERVICE_QNAME);
    }

    public ShopWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOPWSIMPLSERVICE_QNAME, features);
    }

    public ShopWsImplService(URL wsdlLocation) {
        super(wsdlLocation, SHOPWSIMPLSERVICE_QNAME);
    }

    public ShopWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOPWSIMPLSERVICE_QNAME, features);
    }

    public ShopWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShopWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IShopWs
     */
    @WebEndpoint(name = "ShopWsImplPort")
    public IShopWs getShopWsImplPort() {
        return super.getPort(new QName("http://ws.customer.momas.cc/", "ShopWsImplPort"), IShopWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IShopWs
     */
    @WebEndpoint(name = "ShopWsImplPort")
    public IShopWs getShopWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.customer.momas.cc/", "ShopWsImplPort"), IShopWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOPWSIMPLSERVICE_EXCEPTION!= null) {
            throw SHOPWSIMPLSERVICE_EXCEPTION;
        }
        return SHOPWSIMPLSERVICE_WSDL_LOCATION;
    }

}
