package cc.momas.customer.mapper;

import cc.momas.customer.pojo.Consumeorders;
import cc.momas.customer.pojo.ConsumeordersExample;
import cc.momas.customer.pojo.Pager;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsumeordersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int countByExample(ConsumeordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int deleteByExample(ConsumeordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int deleteByPrimaryKey(Integer consumeordersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int insert(Consumeorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int insertSelective(Consumeorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    List<Consumeorders> selectByExample(ConsumeordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    Consumeorders selectByPrimaryKey(Integer consumeordersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") Consumeorders record, @Param("example") ConsumeordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByExample(@Param("record") Consumeorders record, @Param("example") ConsumeordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByPrimaryKeySelective(Consumeorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumeorders
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByPrimaryKey(Consumeorders record);

	List<Consumeorders> selectByPager(Pager<Consumeorders, ConsumeordersExample> pager);
}