package cc.momas.customer.mapper;

import cc.momas.customer.pojo.Memcards;
import cc.momas.customer.pojo.MemcardsExample;
import cc.momas.customer.pojo.Pager;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemcardsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int countByExample(MemcardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int deleteByExample(MemcardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int deleteByPrimaryKey(Integer memcardsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int insert(Memcards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int insertSelective(Memcards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    List<Memcards> selectByExample(MemcardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    Memcards selectByPrimaryKey(Integer memcardsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") Memcards record, @Param("example") MemcardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByExample(@Param("record") Memcards record, @Param("example") MemcardsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByPrimaryKeySelective(Memcards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memcards
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByPrimaryKey(Memcards record);
    
    Memcards selectByMemCardId(String cardId);

	List<Memcards> queryByPager(Pager<Memcards, MemcardsExample> pager);
}