package cc.momas.customer.mapper;

import cc.momas.customer.pojo.Transferlogs;
import cc.momas.customer.pojo.TransferlogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferlogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int countByExample(TransferlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int deleteByExample(TransferlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int deleteByPrimaryKey(Integer transferlogsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int insert(Transferlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int insertSelective(Transferlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    List<Transferlogs> selectByExample(TransferlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    Transferlogs selectByPrimaryKey(Integer transferlogsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") Transferlogs record, @Param("example") TransferlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByExample(@Param("record") Transferlogs record, @Param("example") TransferlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByPrimaryKeySelective(Transferlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transferlogs
     *
     * @mbggenerated Mon Nov 20 16:13:07 CST 2017
     */
    int updateByPrimaryKey(Transferlogs record);
}