create table USERS
(
  ID        NUMBER not null PRIMARY KEY,
  NAME      VARCHAR2(50),
  PASSWORD  VARCHAR2(50),
  TELEPHONE VARCHAR2(15),
  USERNAME  VARCHAR2(50),
  ISADMIN   VARCHAR2(5)
);
create table DISTRICT
(
  ID   NUMBER not null PRIMARY KEY,
  NAME VARCHAR2(50) not null
);
create table STREET
(
  ID          NUMBER not null PRIMARY KEY,
  NAME        VARCHAR2(50),
  DISTRICT_ID NUMBER,
  FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT(ID)
);
create table TYPES
(
  ID   NUMBER not null PRIMARY KEY,
  NAME VARCHAR2(10) not null
);
create table HOUSE
(
  ID          NUMBER PRIMARY KEY,
  USER_ID     NUMBER,
  TYPES_ID     NUMBER,
  TITLE       NVARCHAR2(50),
  DESCRIPTION NVARCHAR2(2000),
  PRICE       NUMBER,
  PUBDATE     DATE,
  FLOORAGE    NUMBER,
  CONTACT     VARCHAR2(100),
  STREET_ID   NUMBER,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (TYPES_ID) REFERENCES TYPES(ID),
  FOREIGN KEY (STREET_ID) REFERENCES STREET(ID)  
);


